[project]
name = 'Light'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.Light]
path = 'contracts/Light.clar'
clarity_version = 2
epoch = 2.4

[contracts.clarity-bitcoin-mini]
path = 'contracts/clarity-bitcoin-mini.clar'
clarity_version = 2
epoch = 2.4

[contracts.pool]
path = 'contracts/pool.clar'
clarity_version = 2
epoch = 2.4

[contracts.sBTC]
path = 'contracts/sBTC.clar'
clarity_version = 2
epoch = 2.4

[contracts.sample-stacking]
path = 'contracts/sample-stacking.clar'
clarity_version = 2
epoch = 2.4

[contracts.staking]
path = 'contracts/staking.clar'
clarity_version = 2
epoch = 2.4

[repl]
clarity_wasm_mode = false
show_timings = false

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
